### ISSUE TITLE
pointsWithinPolygon function does not seem to work

### ISSUE THREAD

**Issue by spydmobile** [bloigge/node-red-contrib-turf#3]
I am trying to access this feature (pointsWithinPolygon) of TURF via your node-red node, my object going into the turf node looks like this:

`object
topic: "pointsWithinPolygon"
payload: array[2]
0: object
type: "FeatureCollection"
features: array[739]
1: object
type: "FeatureCollection"
features: array[33]`

where the first FeatureCollection is points, the second polys. 

I keep getting : "TypeError: Cannot read property 'apply' of undefined"

I have other turf nodes in this flow that work fine. Is this Turf is at 5.x and this is working with node 3.x perhaps?

**Comment by dceejay** [comment]
This can probably now be closed after latest update to 1.0

**Comment by bloigge** [comment]
Yes, with the latest release this works now.
![image](https://user-images.githubusercontent.com/7089726/133385682-413b7ad2-fe32-4742-a0e1-60b6c9af4c73.png)

`[
    {
        "id": "f679ac51893aafbf",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "5dd4f96301094f2d",
        "type": "turf",
        "z": "f679ac51893aafbf",
        "name": "",
        "x": 490,
        "y": 140,
        "wires": [
            [
                "bd2ffadb47979393"
            ]
        ]
    },
    {
        "id": "46a344f271721ee7",
        "type": "turf",
        "z": "f679ac51893aafbf",
        "name": "",
        "x": 490,
        "y": 340,
        "wires": [
            [
                "bd2ffadb47979393"
            ]
        ]
    },
    {
        "id": "5270aefcb213d3ea",
        "type": "debug",
        "z": "f679ac51893aafbf",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1230,
        "y": 240,
        "wires": []
    },
    {
        "id": "83cc6d15e12e1959",
        "type": "inject",
        "z": "f679ac51893aafbf",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 90,
        "y": 240,
        "wires": [
            [
                "2578f6a82a51061b",
                "652c66ca0969cb15"
            ]
        ]
    },
    {
        "id": "2578f6a82a51061b",
        "type": "function",
        "z": "f679ac51893aafbf",
        "name": "Create Points",
        "func": "msg.payload = [  \n    [   \n        [-46.6318, -23.5523],     \n        [-46.6246, -23.5325],     \n        [-46.6062, -23.5513],     \n        [-46.663, -23.554],     \n        [-46.643, -23.557]\n    ]\n];\nmsg.topic = \"points\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 300,
        "y": 140,
        "wires": [
            [
                "5dd4f96301094f2d"
            ]
        ]
    },
    {
        "id": "652c66ca0969cb15",
        "type": "function",
        "z": "f679ac51893aafbf",
        "name": "Create Polygon",
        "func": "msg.payload = [\n    [\n        [     \n            [-46.653,-23.543],     \n            [-46.634,-23.5346],     \n            [-46.613,-23.543],     \n            [-46.614,-23.559],     \n            [-46.631,-23.567],     \n            [-46.653,-23.560],     \n            [-46.653,-23.543] \n        ]\n    ]\n];\nmsg.topic = \"polygon\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 300,
        "y": 340,
        "wires": [
            [
                "46a344f271721ee7"
            ]
        ]
    },
    {
        "id": "0fc4a5ea35b2c320",
        "type": "function",
        "z": "f679ac51893aafbf",
        "name": "PointsWithinPolygon",
        "func": "msg.topic = \"pointsWithinPolygon\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 900,
        "y": 240,
        "wires": [
            [
                "1cc86cc91068911f"
            ]
        ]
    },
    {
        "id": "bd2ffadb47979393",
        "type": "join",
        "z": "f679ac51893aafbf",
        "name": "New Payload",
        "mode": "custom",
        "build": "array",
        "property": "payload",
        "propertyType": "msg",
        "key": "topic",
        "joiner": "\\n",
        "joinerType": "str",
        "accumulate": false,
        "timeout": "",
        "count": "2",
        "reduceRight": false,
        "reduceExp": "",
        "reduceInit": "",
        "reduceInitType": "",
        "reduceFixup": "",
        "x": 690,
        "y": 240,
        "wires": [
            [
                "0fc4a5ea35b2c320"
            ]
        ]
    },
    {
        "id": "1cc86cc91068911f",
        "type": "turf",
        "z": "f679ac51893aafbf",
        "fn": "",
        "name": "",
        "x": 1090,
        "y": 240,
        "wires": [
            [
                "5270aefcb213d3ea"
            ]
        ]
    }
]`
