### ISSUE TITLE
Question : how to specify units for "distance"

### ISSUE THREAD

**Issue by saket424** [bloigge/node-red-contrib-turf#4]
By Default, the distance is computed  in kilometers. Yet to figure out how to pass {units:"miles"} to turf-distance

msg.payload = [msg.payload.features[0].geometry, msg.payload.features[1].geometry];
msg.topic = "distance";

return msg;

**Comment by saket424** [comment]
the documentation says 

var from = turf.point([-75.343, 39.984]);
var to = turf.point([-75.534, 39.123]);
var options = {units: 'miles'};

var distance = turf.distance(from, to, options);

when I try to pass it as the third parameter in my nodered function, I get Invalid unit
msg.payload = [msg.payload.features[0], msg.payload.features[1], {units:'miles'}];
"Error: Invalid unit"

Without the third parameter, it works fine. Anyone can suggest the right syntax ?

**Comment by bloigge** [comment]
Sorry for writing back so late. With the newest release this works now as expected.
