### ISSUE TITLE
How to report issues for the other node `red-contrib-turf-module` you have created ?

### ISSUE THREAD

**Issue by janvda** [bloigge/node-red-contrib-turf#6]
I see that you are also the author of the other turf node:
* https://flows.nodered.org/node/red-contrib-turf-module

I would like to raise an issue for that, but I don't know where to report it.
I can't find its github repository.

FYI the issue I would like to report is that specifying argument `msg.countries[0].country_shape` won't work.
<img width="695" alt="image" src="https://user-images.githubusercontent.com/17238398/207264322-52d1686e-4e74-4706-af6f-b255d6ae3204.png">

but it works when I first uses a change node to copy `msg.countries[0].country_shape`  to `msg.payload` and  then use `msg.payload` as argument in the turf node:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/17238398/207264953-4d477c02-2679-4e85-b697-ce84e3fcef23.png">

**Comment by bloigge** [comment]
Thanks for the report - the other repo can be found here: https://github.com/bloigge/node-red-contrib-turf-module

**Comment by bloigge** [comment]
applied a fix for your issue and also added a link to the github repo to npm / node-red.
